### ISSUE TITLE
add BMAT on the BIDS website

### ISSUE THREAD

**Issue by Remi-Gau** [ColinVDB/BMAT#1]
We have a list of tools and converters on the BIDS website.

BMAT falls in both category, no?

https://bids.neuroimaging.io/benefits.html#benefits

**Comment by ColinVDB** [comment]
Yes, it falls indeed in these categories, thank you for the suggestion

Could you tell me how I can add this to the BIDS website, do I directly edit the page on GitHub, or do I need to make a request ?

Thank you, 

Colin

**Comment by Remi-Gau** [comment]
We are trying to sort of standardize info about the BIDS tooling out there.

You can open a pull request if you want, or I can take care of this later.

To list BMAT as a converter, you would have to add an entry in this yml file:
https://github.com/bids-standard/bids-website/blob/gh-pages/_data/converters.yml

For the other aspects of BMAT (for exmaple dataset management), you would have to add a link manually in this markdown file.
https://github.com/bids-standard/bids-website/blob/1ba3a470bd1098d2bf92d70ba4a5f0909bd1aba7/_pages/benefits.md?plain=1#L47

**Comment by Remi-Gau** [comment]
Opened a PR.

Please have a look when you have time:

https://github.com/bids-standard/bids-website/pull/263/files#diff-4515a73e931b80902516ca6a4e980ae47e71aa6279cefa16cb30618dc3951364
