### ISSUE TITLE
symbol krb5_ser_context_init version krb5_3_MIT not defined in file libkrb5.so.3 with link time reference

### ISSUE THREAD

**Issue by c-m-bauer** [ColinVDB/BMAT#3]
Hi, I have followed the instructions for installation on my ubuntu 18.04, but am getting the following error (see below). The dependencies outlines in requirements are already installed. 

Any suggestions?

Thanks! 

python BMAT.py 
Traceback (most recent call last):
  File "/home/computer/BMAT/BMAT/BMAT.py", line 80, in <module>
    from PyQt5.QtNetwork import QNetworkAccessManager, QNetworkReply, QNetworkRequest
ImportError: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2: symbol krb5_ser_context_init version krb5_3_MIT not defined in file libkrb5.so.3 with link time reference

**Comment by ColinVDB** [comment]
Hi thank you for reporting this issue.

I have never encountered this issue before, but here are some questions/suggestions to try:
- Did you install BMAT and its dependencies into its own virtual environments ? It can happen that some required packages for BMAT does not work with other packages already installed on your computer but not needed for this app. Creating a new virtual environment and redo the installation inside the virtual environment can help this issue. 
- Also, maybe there are new issues from new versions of the python modules that I am not aware of. So here are the detailed versions of the modules that I use and that does seem to work: 
    - python 3.8.17
    - PyQt5==5.12
    - PyQt5-Qt5==5.12
    - PyQt5_sip==4.19.19
    - PyQtWebEngine==5.12
    - PyQtWebEngine-Qt5==5.12.2
   
You can try to reinstall BMAT in its own virtual environment with this packages versions. If this is the issue, I will update the requirements. 

If you have other questions, do not hesitate, 

Thank you, 

Colin
